### This configuration contains the parameters and the keys needed to run the postprocessing of the study.

# Config mad
optics_file: ["config_mad", "optics_file"]
beam_energy_tot_b1: ["config_mad", "beam_config", "lhcb1", "beam_energy_tot"]
beam_energy_tot_b2: ["config_mad", "beam_config", "lhcb2", "beam_energy_tot"]
ions: ["config_mad", "ions"]

# Knobs
qx_b1: ["config_collider", "config_knobs_and_tuning", "qx", "lhcb1"]
qx_b2: ["config_collider", "config_knobs_and_tuning", "qx", "lhcb2"]
qy_b1: ["config_collider", "config_knobs_and_tuning", "qy", "lhcb1"]
qy_b2: ["config_collider", "config_knobs_and_tuning", "qy", "lhcb2"]
dqx_b1: ["config_collider", "config_knobs_and_tuning", "dqx", "lhcb1"]
dqx_b2: ["config_collider", "config_knobs_and_tuning", "dqx", "lhcb2"]
dqy_b1: ["config_collider", "config_knobs_and_tuning", "dqy", "lhcb1"]
dqy_b2: ["config_collider", "config_knobs_and_tuning", "dqy", "lhcb1"]
i_oct_b1: ["config_collider", "config_knobs_and_tuning", "knob_settings", "i_oct_b1"]
i_oct_b2: ["config_collider", "config_knobs_and_tuning", "knob_settings", "i_oct_b2"]
on_disp: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_disp"]
on_crab1: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_crab1"]
on_crab5: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_crab5"]
on_alice_normalized: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_alice_normalized"]
on_lhcb_normalized: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_lhcb_normalized"]

# Knobs that might be optimized for levelling purposes 
on_x1: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x1"]
final_on_x1: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x1"]
on_x2: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x2"]
final_on_x2: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x2"]
on_x2h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x2h"]
final_on_x2h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x2h"]
on_x2v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x2v"]
final_on_x2v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x2v"]
on_x5: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x5"]
final_on_x5: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x5"]
on_x8: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x8"]
final_on_x8: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x8"]
on_x8h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x8h"]
final_on_x8h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x8h"]
on_x8v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_x8v"]
final_on_x8v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_x8v"]
on_sep1: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep1"]
final_on_sep1: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep1"]
on_sep2: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep2"]
final_on_sep2: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep2"]
on_sep2h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep2h"]
final_on_sep2h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep2h"]
on_sep2v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep2v"]
final_on_sep2v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep2v"]
on_sep5: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep5"]
final_on_sep5: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep5"]
on_sep8: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep8"]
final_on_sep8: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep8"]
on_sep8h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep8h"]
final_on_sep8h: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep8h"]
on_sep8v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "on_sep8v"]
final_on_sep8v: ["config_collider", "config_knobs_and_tuning", "knob_settings", "final_on_sep8v"]


# Configuration beam-beam
sigma_z: ["config_collider", "config_beambeam", "sigma_z"]
nemitt_x: ["config_collider", "config_beambeam", "nemitt_x"]
nemitt_y: ["config_collider", "config_beambeam", "nemitt_y"]
pattern_fname: ["config_collider", "config_beambeam", "mask_with_filling_pattern", "pattern_fname"]
i_bunch_b1: ["config_collider", "config_beambeam", "mask_with_filling_pattern", "i_bunch_b1"]
i_bunch_b2: ["config_collider", "config_beambeam", "mask_with_filling_pattern", "i_bunch_b2"]
cross_section: ["config_collider", "config_beambeam", "cross_section"]

# Variables that are optimized
num_particles_per_bunch: ["config_collider", "config_beambeam", "num_particles_per_bunch"]
final_num_particles_per_bunch: ["config_collider", "config_beambeam", "final_num_particles_per_bunch"]
luminosity_ip1_without_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip1_without_beam_beam"]
luminosity_ip1_with_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip1_with_beam_beam"]
luminosity_ip2_without_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip2_without_beam_beam"]
luminosity_ip2_with_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip2_with_beam_beam"]
luminosity_ip5_without_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip5_without_beam_beam"]
luminosity_ip5_with_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip5_with_beam_beam"]
luminosity_ip8_without_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip8_without_beam_beam"]
luminosity_ip8_with_beam_beam: ["config_collider", "config_beambeam", "luminosity_ip8_with_beam_beam"]
Pile-up_ip1_without_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip1_without_beam_beam"]
Pile-up_ip1_with_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip1_with_beam_beam"]
Pile-up_ip2_without_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip2_without_beam_beam"]
Pile-up_ip2_with_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip2_with_beam_beam"]
Pile-up_ip5_without_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip5_without_beam_beam"]
Pile-up_ip5_with_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip5_with_beam_beam"]
Pile-up_ip8_without_beam_beam: ["config_collider", "config_beambeam", "Pile-up_ip8_without_beam_beam"]

# Config simulation
beam: ["config_simulation", "beam"]
delta_max: ["config_simulation", "delta_max"]